# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "monitor" do |monitor|
    monitor.vm.hostname = "monitor"
    monitor.vm.network "private_network", ip: "192.168.56.104"
    config.vm.box = "generic/debian12"
  end
  
  config.vm.define "moodle" do |moodle|
    moodle.vm.hostname = "moodle"
    moodle.vm.network "private_network", ip: "192.168.56.12"
    config.vm.box = "generic/debian12"
  end
  
  config.vm.define "jitsimeet" do |jitsimeet|
    jitsimeet.vm.hostname = "jitsimeet"
    jitsimeet.vm.network "private_network", ip: "192.168.56.163"
    config.vm.box = "generic/debian12"
  end

  #config.vm.provider "virtualbox" do |vb|
  #  vb.gui = false
  #  vb.memory = "2048"
  #  vb.cpus = 2
  #end

#config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct:true
#config.vm.usable_port_range = (8000..9000)
end
  



