# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "monitor" do |monitor|
    monitor.vm.hostname = "monitor"
    monitor.vm.network "private_network", ip: "192.168.56.104"
    config.vm.box = "generic/debian12"
  end
  
  config.vm.define "target1" do |target1|
    target1.vm.hostname = "target1"
    target1.vm.network "private_network", ip: "192.168.56.12"
    config.vm.box = "generic/debian12"
  end
  
  config.vm.define "target2" do |target2|
    target2.vm.hostname = "target2"
    target2.vm.network "private_network", ip: "192.168.56.163"
    config.vm.box = "generic/debian12"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../provisioning/playbook.yml"
    ansible.inventory_path = "../provisioning/inventory.ini"
  end

  #config.vm.provider "virtualbox" do |vb|
  #  vb.gui = false
  #  vb.memory = "2048"
  #  vb.cpus = 2
  #end

#config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct:true
#config.vm.usable_port_range = (8000..9000)
end
  



