global:
  resolve_timeout: 2m
  smtp_require_tls: false

route:
  group_by: ['altername']
  # Send all notifications to me.
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5s
  receiver: 'rocketchat'

receivers:
#- name: 'email-me'
#  email_configs:
#  - to: 
#    from: 
#    smarthost: "smtp.gmail.com:587"
#   auth_username: 
#    auth_identity: 
#    auth_password: 

- name: 'rocketchat'
  webhook_configs:
    - send_resolved: true
      url: ''

#  telegram_configs:
#  - bot_token: 
#    api_url: https://api.telegram.org
#    chat_id: 
#    parse_mode: ''
