---
- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Modifier le port HTTP de Grafana
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;?http_port ='
    line: 'http_port = 8081'
    state: present

- name: Start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Enable the Grafana service
  systemd:
    name: grafana-server
    enabled: yes
  become: true

- name: Redémarrer le service Grafana après modification du port
  systemd:
    name: grafana-server
    state: restarted

#- name: "UFW - Allow 3000 port"
#  ufw:
#    rule: allow
#    port: 3000
#    proto: tcp
